### ISSUE TITLE
New breed Banescale

### ISSUE THREAD

**Issue by jill-ye** [JiYouMCC/FlightRisingTool#117]
![image](https://user-images.githubusercontent.com/7357434/71136934-6327e900-2241-11ea-8b76-3dd6eb949a92.png)
Banescale古戟
Common

|   | **Plentiful 丰富** | **Common 常见** | **Uncommon 罕见** | **Limited 限定** | **Rare稀有** |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| **Primary**  | 基础 Basic  | Laced, Marble大理石, Savannah, Tiger | Cherub, Chevron 倒人字形, Jaguar, Ragged 烂衣 | Candycane 拐棍糖, Pinstripe, Poison, Skink | Metallic, Petals  |
| **Secondary**  | 基础 Basic  | Edged, Mottle, Safari, Stripes | Arrow, Rosette, Seraph, Tear | Spinner, Sugarplum, Toxin, Trail | Alloy, Butterfly  |
| **Tertiary**  | 基础 Basic  | Contour, Trimmings | Crackle, Lace, Ghost, Ringlets | Porcupine, Skeletal, Squiggle | Fans, Filigree, Plumage, Wraith |

**Comment by JiYouMCC** [comment]
待翻译部分:
Banescale Primary Gene List
Banescale Secondary Gene List
Banescale Tertiary Gene List

----
Marble
Chevron
Ragged
Candycane

----
Mottle
Arrow
Tear
Sugarplum

----
Trimmings
Porcupine
Skeletal
Squiggle
Fans
Plumage
Wraith
