### ISSUE TITLE
Layout for the Breeding Tool Page Not Space Friendly

### ISSUE THREAD

**Issue by fictivecreations** [JiYouMCC/FlightRisingTool#143]
Hey there!
I recently was made aware of your tool as a replacement for another I was using, specifically the ratio calculation for a specific end result dragon.

Unfortunately I find the layout of the page very difficult to work with as I have to scroll up and down between the parents and the calculate button as I plug in different options. 
It would be great if the page could be made to be more compact.

If you're open to contributions to the project I would be really happy to help make these changes! (front end web development is my day job).

**Comment by JiYouMCC** [comment]
@sunlanterns thank you for comment.
I'm not good at UI. You can try to draw a draft or something if you are interesting in it. I can try to change it.
Or if you are more interested in this, would you like to be a contributor of this project? 😄 You can update the UI and create Pull request.
Currently, I use bootstrap 3.5+ which maybe out of date.

**Comment by fictivecreations** [comment]
@JiYouMCC 
I'd be happy to contribute! I'll try my hand at updating it this coming weekend.

**Comment by JiYouMCC** [comment]
@sunlanterns I've invited you.
If you want to change the UI platform, let me know.
But I think bootstrap 3.5+ should meet the requirement.
Don't be so hurry. Just update this like playing game.
For more details, we can discuss under this Issue.

**Comment by fictivecreations** [comment]
@JiYouMCC I've just put up a PR with my suggested changes and a few other fixes here: #153
