### ISSUE TITLE
Missing Genes

### ISSUE THREAD

**Issue by LPS100** [JiYouMCC/FlightRisingTool#161]
Hello, I don't know how to make a pull request, so I'm listing all the missing genes from the Tool.

**Modern:**
- Missing Primary and Secondary Gem Gene: Pharaoh and Sarcophagus.
- The newest Primary and Secondary Arlo Gene combo, Ground, and Fissure.

**Banescale:**
- Missing Tapir Primary and new Tertiary gene, Gliders.

**Gaoler:**
- Missing new Tertiary gene, Pinions.

**Veilspun:**
- Missing new Tertiary gene, Angler.

I unfortunately don't know the rarity of the newer genes, though list-wise, those are the missing ones.

**Comment by JiYouMCC** [comment]
Thank you! I will update it before March. Sorry I'm busy recently.

**Comment by JiYouMCC** [comment]
I've added the missing genes you mentioned. But some genes' rarity may not correct. Will check later
