### ISSUE TITLE
Language Switch

### ISSUE THREAD

**Issue by CharlotteHan** [JiYouMCC/FlightRisingTool#53]
增加功能面板中英文一键切换功能

考虑到中文翻译的多样性和接受程度，选择框中的中英文同时出现部分保留方便用户选择

**Comment by JiYouMCC** [comment]
https://github.com/coderifous/jquery-localize

**Comment by JiYouMCC** [comment]
@CharlotteHan  https://github.com/JiYouMCC/FlightRisingTool/blob/multi-language/lg/basic-en.json
有空来吐槽下翻译，不然我就直接pull了

**Comment by CharlotteHan** [comment]
@JiYouMCC 
感觉看不懂英文的国际友人估计不会移动到右上角，前面加个language：中文，下拉language: English比较好？

**Comment by JiYouMCC** [comment]
@CharlotteHan 我去参考下其他网站布局。。

**Comment by JiYouMCC** [comment]
@CharlotteHan 那个小地球咋样哇哈哈哈。。。

我还要把下拉菜单里面的东西给分离掉。。分离前先别介绍给外国友人。。
